Fix `gcc-13` build failures: missing `<cstdint>` includes
Without the change build fails on `gcc-13` as:

    In file included from /build/source/components/misc/stringops.hpp:8,
                     from /build/source/components/settings/settings.cpp:6:
    /build/source/components/misc/utf8stream.hpp:11:13: error: 'uint32_t' does not name a type
       11 |     typedef uint32_t UnicodeChar;
          |             ^~~~~~~~
    /build/source/components/misc/utf8stream.hpp:5:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
        4 | #include <cstring>
      +++ |+#include <cstdint>